only_rules:
    - colon
    - line_length
    - comma
    - trailing_whitespace
    - leading_whitespace
    - trailing_newline
    - todo
    - no_space_in_method_call
    - vertical_whitespace
    - return_arrow_whitespace
    - operator_usage_whitespace
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - unused_import
    - prohibited_interface_builder

line_length:
    warning: 150
    error: 200

trailing_whitespace:
    ignores_empty_lines: true
